#!/bin/bash
# Bootstrap script used to run setup tasks for Misago client image

# Text styles
RED='\033[0;31m'
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

# Utility functions used by action commands
error() {
    echo -e "${RED}Error:${NORMAL} $1"
}
# Commands
install_plugins() {
    # If plugins are present, install their node requirements
    if [[ ! -d /client/plugins ]]; then
        echo "SKIP"
        exit 0
    fi

    # Run setup script for plugins JS
    node setupPlugins.js
}

# Command dispatcher
if [[ $1 ]]; then
    if [[ $1 = "start" ]]; then
        install_plugins
        npm run i18n-compile
        npm run start
    elif [[ $1 = "plugins" ]]; then
        install_plugins
    else
        invalid_argument $1
        echo -e "Invalid argument: ${RED}$1${NORMAL}"
        exit 1
    fi
else
    error "This command needs to be ran with an argument."
    exit 1
fi
